global:
  scrape_interval: 30s  

scrape_configs:
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:3000']

  - job_name: 'reporter'
    static_configs:
      - targets: ['reporter:6000']

  - job_name: 'fb-collector'
    static_configs:
      - targets: ['fb-collector:4000']

  - job_name: 'ttk-collector'
    static_configs:
      - targets: ['ttk-collector:5000']